function output = Augmented_Kalman(data,param)
%% AUGMENTED_KALMAN: runs the generalized correction procedure in Burghoff et al., Optics Letters (2019).
% If you found this useful in your research, then please cite our work!
% Requirements:
% 1. Newer versions of MATLAB with implicit expansion
% 2. XSum: sum with error compensation (https://www.mathworks.com/matlabcentral/fileexchange/26800-xsum)
%
% Inputs:
%   data: A structure that contains two required fields and a third optional one:
%       sn:        a complex signal represented by a column vector. If there are
%                  multiple columns, all will be corrected by the corr_sn'th column
%       dt:        the timestep
%       corr_sn :  (optional) which signal to use for the correction (default: 1st signal)
%   param: A structure that configures the parameters of the correction, generated by running AK_Params()

%%

function ret = paramis(fieldname,check)
    if isfield(param,fieldname) && isequal(param.(fieldname),check)
        ret = true;
    else
        ret = false;
    end
end
doEM = isequal(param.EM,1) || isequal(param.EM,'ekf');

if ~isfield(param,'knownfD') && isfield(param,'knownfr')
    param.knownfD = param.knownfr;
end
if ~isfield(param,'fD_range') && isfield(param,'fr_range')
    param.fD_range = param.fr_range;
end


%% Get data from structures
% To avoid precision issues, scale time to be in units of the approximate rep rate
% param = Initialize_Params(param);
corr_sn=1; if isfield(data,'corr_sn'); corr_sn = data.corr_sn; end
dt= data.dt; sn= data.sn(:,corr_sn); N=length(data.sn);

Ts = 1/mean(param.fD_range);
dt = dt/Ts;
param.fD_range = param.fD_range*Ts;
ts=dt*(0:N-1)';

%% Figure out measurement noise standard deviation from white noise level, then multiply by param.excess_noise
fs = 1/(N*dt)*(0:N-1)';
fss = fftshift(fs); fss(1:find(diff(fss)<0))=fss(1:find(diff(fss)<0))-1/dt;     % fftshifted-fs
Fsn = fft(sn);

psd  = fftshift(abs(Fsn)).^2*dt/N;
npsd = mean(psd(abs(fss)>=1/dt/2*0.9));
nstd = sqrt((npsd/2)*(1/dt));                                                   % noise in each quadrature
nstd = nstd*param.excess_noise;
% figure; semilogy(fss,psd);                                  % for spying
% hold all; p=semilogy(fss,fftshift(abs(fft(nstd*(randn(N,1)+i*randn(N,1)))).^2*dt/N)); uistack(p,'bottom');

[~,ml]=max(psd);
maxf = fss(ml); stdf = sqrt(sum(psd.*(fss-maxf).^2)/sum(psd));
cdf = cumsum(psd)/sum(psd); [~,ml]=min(abs(cdf-0.5)); medf=fss(ml);
%% Kalman filter structure and initial values
fDhi = param.fD_range(2); fDlo = param.fD_range(1);

% Initial values
fD0 = (fDlo+fDhi)/2;    
pD0 = 0;                   % phases                         
f00 = 0;
p00 = 0;

givenn = isfield(param,'n') &&  ~any(isnan(param.n));
if ~givenn, n = round((-1/dt-f00)/fDlo/2):round((1/dt-f00)/fDlo/2);
else,       n = reshape(param.n,1,length(param.n));
end
Nl = length(n);
num_stds = param.global_search_stds;

% Initial covariances
PfD  = ((fDhi-fDlo)/2)^2*10;           % rep rate
Pf0  = (stdf)^2*10;                    % rep rate
% Pf0  = (mean([fDhi,fDlo]))^2/100;                    % rep rate
Pp0 =  (2*pi)^2*10;                 % defined at t=0
PpD =  (2*pi)^2*10;                 % defined at t=0

%% Divide data into batches
% In pulsed mode, signal is sparse so apodizing can save a lot of time /
% memory. This is somewhat experimental and untested, though.
M0 = ceil(1/((fDlo+fDhi)/2*dt));
if isfield(param,'pulsed_mode_apodization') && ~isnan(param.pulsed_mode_apodization)
    [~,locs]=findpeaks(abs(sn).^2,'MinPeakDistance',0.75*M0);
    M = ceil(param.pulsed_mode_apodization/((fDlo+fDhi)/2*dt));
    if mod(M,2)==1, Mr = [-(M-1)/2,(M-1)/2];
    else,           Mr = [-M/2+1,M/2]; end
    starts = locs(2:end-1)'+Mr(1); stops = locs(2:end-1)'+Mr(2);    % starts and stops of each batch processed by filter
    fstops = [starts(2:end),locs(end)'+Mr(1)]-1;                    % stops of the full batches that include data in between
else
    M = M0;
    starts = 1:M:length(sn); stops = M:M:length(sn);
%     if stops(end)~=length(sn), stops(end+1)=length(sn); end         % added 2020.11.11
    starts=starts(1:length(stops));
    fstops = stops;
%     fstops(end) = length(sn);                                         % added 2020.11.12
end

Nb = length(starts);
bl = cell2mat(arrayfun(@(x,y)(x:y)',starts,stops,'un',0));   % batch locations                                             
snr = sn(bl); tsf = ts(bl);

Md =[NaN,diff(starts)];                                      % distance from a start to the previous one
lgf = fstops-starts+1;                                       % length of the kth full batch
vr = starts(1):stops(end); % valid range

%% Create and run Kalman filter
% State structure
lp0=1; lpD=2; lf0 = 3; lfD = 4;
x0 = [p00;pD0;f00;fD0];
P0 = diag([Pp0;PpD;Pf0;PfD]);

% Process function
F1 = eye(length(x0));                   % single timestep
F1(lpD,lfD)=F1(lpD,lfD)+2*pi*dt;
F1(lp0,lf0)=F1(lp0,lf0)+2*pi*dt;

Fs = arrayfun(@(x)F1^x,Md,'un',0);
Q = param.Q;
Qs = arrayfun(@(x)Q/M0*x,Md,'un',0);

% Nonlinear measurement function
tk = dt*(0:M-1)';
function [ho,Ho] = hH(x,GIi,GIni)
%   Method 1: Explicit summation, slower for large Nl (takes A as argument)
%     expv = A.'.*exp(i*( x(lp0)+2*pi*x(lf0)*tk + n.*(x(lpD)+2*pi*x(lfD)*tk) ));
%     hc = sum(expv,2); ho = [real(hc);imag(hc)]; 
%     if nargout>1
%         Hc = i*[hc,sum(expv.*n,2),2*pi*sum(expv.*tk,2),2*pi*sum(expv.*tk.*n,2)];
%         Ho = [real(Hc);imag(Hc)];
%     end
%   Method 2: Interpolate over FFT, faster for large Nl
    tp = (x(lpD) + 2*pi*x(lfD)*tk)/(2*pi); tp=tp-floor(tp);
    exp0 = exp(1i*(x(lp0)+2*pi*x(lf0)*tk));
    hc = exp0.*GIi(tp);
    ho = [real(hc);imag(hc)]; 
    if nargout>1
        GInv = GIni(tp);
        Hc = 1i*[hc,exp0.*GInv    ,2*pi*hc.*tk         ,2*pi*exp0.*GInv.*tk];
        Ho = [real(Hc);imag(Hc)];
    end
end
% R = eye(M*2)*nstd^2;            % noise is sigma^2 in each quadrature

% function [ho,Ho] = hHf(x,GIi,GIni,Min)
%     tkf = dt*[0:Min-1]';
%     tp = (x(lpD) + 2*pi*x(lfD)*tkf)/(2*pi); tp=tp-floor(tp);
%     exp0 = exp(i*(x(lp0)+2*pi*x(lf0)*tkf));
%     hc = exp0.*GIi(tp);
%     ho = [real(hc);imag(hc)]; 
%     if nargout>1
%         GInv = GIni(tp);
%         Hc = 1i*[hc,exp0.*GInv    ,2*pi*hc.*tkf         ,2*pi*exp0.*GInv.*tkf];
%         Ho = [real(Hc);imag(Hc)];
%     end
% end


% Setup an interpolant for the interferogram p(t)
ZPF = 5;                                        % zero padding factors
fsi = (-ZPF*max(abs(n)):ZPF*max(abs(n)))';
imfn = find(ismember(fsi,n));
Fsi = zeros(size(fsi)); Fsi(imfn)=zeros(size(n));
VF = length(Fsi)*ifft(ifftshift(Fsi)); VF=[VF;VF(1)];
tf = 1/(length(Fsi)*1)*(0:length(Fsi))';
[GI,GIn] = deal(griddedInterpolant(tf,VF,'cubic'));    % change Values in loop instead of regenerating, faster than interp1
function Vo = Amplitude_to_IFG(Ai)                     % calculates p(t) from amplitudes using FFT
    Fsi(imfn)=Ai;
    Vo = length(Fsi)*ifft(ifftshift(Fsi)); Vo=[Vo;Vo(1)];
end

% Setup a demodulation function that uses FFT instead of calculating an
% exponential explicitly, which is slow when Nl is large
function yd = FFT_Demod(x,y)
    fd = 1/(ZPF*length(y)*dt)*(0:ZPF*length(y)-1)'; fds = fftshift(fd); zi=find(fds==0); fds(1:zi-1)=fds(1:zi-1)-1/dt;
    GIf = griddedInterpolant(fds,fds,'cubic','none');
    GIf.Values = fftshift(fft(y,ZPF*length(y)));
    Fy = GIf(x(lf0)+n*x(lfD)); Fy(isnan(Fy))=0;
    yd = exp(-1i*(x(lp0)+n*x(lpD))) .* Fy / length(y);
end

% Single-batch measurement update: a grid search over MAP candidates followed
% by an iterated EKF, linearized around the prediction (xkkm1,Pkkm1). Uses the
% current amplitude estimate Av for batch index k and writes xkk,Pkk. Pulled out
% of the main loop so it can be reused by both the forward and backward passes.
function batch_update()
    GI.Values  = Amplitude_to_IFG(Av);                      % Prepare interpolaters for these amplitudes
    GIn.Values = Amplitude_to_IFG(Av.*n');
    meas = snr(:,k);

    %% Find candidate local minima of MAP using a grid search
    % Rows: f_0   (offset freq)
    % Cols: phi_D (rep rate phase)
    % 3s:   f_Ds  (rep rate freqs)
    pjs = xkkm1(lpD) + pj0;
    pj =  pjs  (pjs  >=xkkm1(lpD)-num_stds*sqrt(Pkkm1(lpD,lpD)) & pjs  <=xkkm1(lpD)+num_stds*sqrt(Pkkm1(lpD,lpD)));

    xkkm1(lfD) = median([fDlo+eps,xkkm1(lfD),fDhi-eps]);
%     fD1 = [1/xkkm1(lfD)/dt:1/fDlo/dt].'; fD2 = [1/xkkm1(lfD)/dt:-1:1/fDhi/dt].';
%     fDs0 = 1./[flipud(fD1(2:end));fD2]./dt; fDs0 = reshape(fDs0,1,1,length(fDs0));
    fD1 = (xkkm1(lfD):-1/M*xkkm1(lfD)/2:fDlo)'; fD2 = (xkkm1(lfD):1/M*xkkm1(lfD)/2:fDhi)';
    fDs0 = [flipud(fD1(2:end));fD2]; fDs0 = reshape(fDs0,1,1,length(fDs0));
    fDs = fDs0(fDs0>=xkkm1(lfD)-num_stds*sqrt(Pkkm1(lfD,lfD)) & fDs0<=xkkm1(lfD)+num_stds*sqrt(Pkkm1(lfD,lfD)));

    f0ss = 1/(ZPF*M*dt)*(0:ZPF*M-1)'; f0ss = fftshift(f0ss); zi=find(f0ss==0); f0ss(1:zi-1)=f0ss(1:zi-1)-1/dt;
    f0ss = xkkm1(lf0)-f0ss;       % f0 sample frequencies
    gf0 = find((f0ss>=xkkm1(lf0)-num_stds*sqrt(Pkkm1(lf0,lf0)) & f0ss<=xkkm1(lf0)+num_stds*sqrt(Pkkm1(lf0,lf0))));
    f0s =  f0ss(gf0);

    % To prevent huge global searches, reduce frequency search when Flj would be too large
    % May want to fiddle with this for large problems
    numsearch = length(f0s)*length(pj)*length(fDs); nss = num_stds; 
    while numsearch > param.global_search_maxsize          
        nss = nss/sqrt(numsearch/param.global_search_maxsize);
        fDs = fDs0( fDs0>=xkkm1(lfD) -nss*sqrt(Pkkm1(lfD,lfD))  & fDs0<=xkkm1(lfD)+nss*sqrt(Pkkm1(lfD,lfD)));
        gf0 = find((f0ss>=xkkm1(lf0) -nss*sqrt(Pkkm1(lf0,lf0))  & f0ss<=xkkm1(lf0)+nss*sqrt(Pkkm1(lf0,lf0))));
        f0s =  f0ss(gf0);
%         pj =  pjs  (pjs  >=xkkm1(lpD)-nss*sqrt(Pkkm1(lpD,lpD)) & pjs  <=xkkm1(lpD)+nss*sqrt(Pkkm1(lpD,lpD)));
        numsearch = length(f0s)*length(pj)*length(fDs);
    end

%     k

    tp = (pj+ 2*pi*fDs.*tk)/(2*pi); tp=tp-floor(tp); % numel(tp)
    Pkj = GI(tp);
    Flj = fftshift(fft(conj(meas.*exp(-1i*2*pi*xkkm1(lf0)*tk)).*Pkj,ZPF*M),1);
    Flj = Flj(gf0,:,:); 

    C = sum(abs(meas).^2);
    Slj = repmat(sum(abs(Pkj).^2,1),size(Flj,1),1,1);

    % Find optimal phi_0 for each point using Newton's method
    Pi = Pkkm1^-1;
    C2 = Pi(lp0,lpD)*(pj-xkkm1(lpD)) + Pi(lp0,lf0)*(f0s-xkkm1(lf0)) + Pi(lp0,lfD)*(xkkm1(lfD)-xkkm1(lfD));
    M00 = Pi(lp0,lp0);
    aFlj = angle(Flj); mFlj = abs(Flj);
    pn = 2*pi*round(1/2/pi*(xkkm1(lp0) - C2/M00 + aFlj)) - aFlj;
    for iN=1:3
        pn = pn - (Pi(lp0,lp0)*(pn-xkkm1(lp0))+C2 + 1/nstd^2*mFlj.*sin(pn+aFlj)) ./ ...
                  (M00 + 1/nstd^2*mFlj.*cos(pn+aFlj));
    end

    % Calculate J(x), the MAP function
    eP = (pn-xkkm1(lp0))        .*(Pi(lp0,lp0)*(pn-xkkm1(lp0))+Pi(lp0,lpD)*(pj-xkkm1(lpD)) + Pi(lp0,lf0)*(f0s-xkkm1(lf0)) + Pi(lp0,lfD)*(xkkm1(lfD)-xkkm1(lfD))) + ...
         (pj-xkkm1(lpD))        .*(Pi(lpD,lp0)*(pn-xkkm1(lp0))+Pi(lpD,lpD)*(pj-xkkm1(lpD)) + Pi(lpD,lf0)*(f0s-xkkm1(lf0)) + Pi(lpD,lfD)*(xkkm1(lfD)-xkkm1(lfD))) + ...
         (f0s-xkkm1(lf0))       .*(Pi(lf0,lp0)*(pn-xkkm1(lp0))+Pi(lf0,lpD)*(pj-xkkm1(lpD)) + Pi(lf0,lf0)*(f0s-xkkm1(lf0)) + Pi(lf0,lfD)*(xkkm1(lfD)-xkkm1(lfD))) + ...
         (xkkm1(lfD)-xkkm1(lfD)).*(Pi(lfD,lp0)*(pn-xkkm1(lp0))+Pi(lfD,lpD)*(pj-xkkm1(lpD)) + Pi(lfD,lf0)*(f0s-xkkm1(lf0)) + Pi(lfD,lfD)*(xkkm1(lfD)-xkkm1(lfD)));
    eR = (C + Slj - 2*real(Flj.*exp(1i*pn)))/nstd^2;
    elj = eR + eP;

    % Pick a few candidate minima from the grid
    Nls = min(15,numel(elj));
    [~,mls]=mink(elj(:),Nls);
    [mrs,mcs,m3s]=ind2sub(size(elj),mls);
    xls = zeros(4,Nls+1);  
    for il=1:Nls
        mf0 = f0s(mrs(il)); mpD = pj(mcs(il)); mfD = fDs(m3s(il));
        mp0 = pn(mrs(il),mcs(il),m3s(il));
        xls(:,il) = [mp0;mpD;mf0;mfD];
    end
    xls(:,end) = xkkm1;

    %% Amongst all candidates, do iterated EKF
    Pi = Pkkm1^-1; 
    Ps = ones(1,size(xls,2))*Inf;
    [Hs,xs,sks] = deal(cell(1,size(xls,2)));

    for ic=1:size(xls,2)
        xl = xls(:,ic);         % candidate minima of MAP
        Pl = Inf; keepgoing = 1;
        while keepgoing
            [hv,Hv]=hH(xl,GI,GIn);                          
            Pn = sum(abs(hv-[real(meas);imag(meas)]).^2)/nstd^2 + (xl-xkkm1)'*(Pi*(xl-xkkm1));
            if Pl-Pn < .01*Pl
                keepgoing = 0;
            end
            Pl = Pn;
            yk = [real(meas);imag(meas)]-hv-Hv*(xkkm1-xl);  
            xl = xkkm1 + Pkkm1*((Hv'*Hv*Pkkm1+nstd^2*eye(4))\(Hv'*yk));
            % The above line is just a speed-optimized version of the usual
            % Kalman filter update, with K=P*H'/(H*P*H'+R). (It makes use
            % of the identity H'/(H*P*H'+R)=I/(H'*H*P+r*I)*H', which
            % is valid when R is diagonal and has diag(R)=r*I.
            % Kk = Pkkm1*((Hv'*Hv*Pkkm1+nstd^2*eye(4))\(Hv'));
        end
        sks{ic} = hH(xl,GI,GIn)-[real(meas);imag(meas)];
        Ps(ic) = sum(abs(sks{ic}).^2)/nstd^2 + (xl-xkkm1)'*(Pi*(xl-xkkm1));
        Hs{ic} = Hv; xs{ic}=xl;
    end
    [~,ml]=min(Ps);
    Hv=Hs{ml}; xkk=xs{ml}; %sk=sks{ml};
    Pkk = (eye(4) - Pkkm1*((Hv'*Hv*Pkkm1+nstd^2*eye(4))\(Hv'*Hv)))*Pkkm1;   % speed optimized
end


% tk1 = dt*[0:fstops(1)-starts(1)+1]';
% function expv = expn(x)
%     expv = exp(-i*( x(lp0)+2*pi*x(lf0)*tk1 + n.*(x(lpD)+2*pi*x(lfD)*tk1) ));
% end

% Other initialization steps
pj1 = 0:-2*pi*fDlo*dt:-pi; pj2 = 0:2*pi*fDlo*dt:pi;
pj0 = [fliplr(pj1),pj2(2:end)];         % densest phi_r grid we might need

givenA  = isfield(param,'knownA') && ~any(isnan(param.knownA));
givenf0 = isfield(param,'knownf0') && ~any(isnan(param.knownf0));
givenfD = isfield(param,'knownfD') && ~any(isnan(param.knownfD));
if ~givenA
    An = ones(Nl,Nb)*NaN;
%     An(:,1) = mean(expn(x0).*sn(starts(1):fstops(1)),1).';
%     An(:,1) = FFT_Demod(x0,[snr(:,1);zeros(lgf(1)-M,1)]).';
    An(:,1) = FFT_Demod(x0,sn(starts(1):fstops(1))).';
else
    An = param.knownA .* ones(1,Nb);
end
initk = 0;
if isfield(param,'initfrac')
    initk = floor(param.initfrac*Nb);
end
if isfield(param,'init_batches')
    initk = param.init_batches;
end
initsleft = param.Ninits;
if isinf(initsleft)
    lastf = []; Ninits=0;
end


%% Main loop
tic; lastplot = 0;
[xk,dPkk] = deal(zeros(Nb,length(x0)));
[xkkm1s,Ck,Pkkm1s,Pkks]= deal(cell(Nb,1));
pkk = zeros(M,Nb);
warning('off','MATLAB:nearlySingularMatrix'); 
if param.plotme
    fh  = dfigure('DPosition',[1,1.25],'DName','Augmented Kalman');
    ax1 = subplot(2,2,1,'Parent',fh);
    % ax2 = subplot(2,2,2,'Parent',fh);
    ax3 = subplot(2,2,3,'Parent',fh);
    ax4 = subplot(2,2,4,'Parent',fh);
end
did_init = false; pxkn=NaN;
k=1; 
while k<=Nb
%     k
    if k==1
        xkkm1 = x0;
        Pkkm1 = P0;
    else
        xkkm1 = Fs{k}*xkk;
        Pkkm1 = Fs{k}*Pkk*Fs{k}' + Qs{k};
        Pkkm1=(Pkkm1+Pkkm1')/2;
    end
        
    if k>1
        Ck{k} = Pkk*Fs{k}'/Pkkm1;
        xkkm1s{k} = xkkm1;
    end
    if doEM
        Pkkm1s{k} = Pkkm1;
    end
    
    fmeas = sn(starts(k):fstops(k));
    if givenA
        Av = param.knownA;
    else
        nn = find(~isnan(An(1,:)));
        Av = sum(An(:,nn).*lgf(nn),2)./sum(lgf(nn));        % weighted sum
        Av(abs(xkkm1(lf0)+n*xkkm1(lfD))>1/dt) = 0;          % Ensure any lines outside the Nyquist band are 0
    end

    batch_update();                                         % grid search + iterated EKF; writes xkk, Pkk

    % Following state update, demodulate batch
    if ~givenA
        An(:,k) = FFT_Demod(xkk,fmeas).';
    end
    
    hv=hH(xkkm1,GI,GIn); pkk(:,k)=real(hv(1:M))+1i*(hv(M+1:end)); % predicted value
    
    xk(k,:) = reshape(xkk,1,length(x0));
    dPkk(k,:)=reshape(diag(Pkk),1,length(x0));
    Pkk = (Pkk+Pkk')/2;
    if doEM, Pkks{k} = Pkk; end

    % Plots
    if (toc - lastplot > 0.5 | k==Nb) && param.plotme
        pxk = xk;
        if ~isnan(pxkn)
            pxk(1:size(pxkn,1),:) = pxkn;
        end

        p = plot(ax3, mean(tsf(:,pxk(:,lfD)~=0),1), pxk(pxk(:,lfD)~=0,lfD)/Ts);
        xyt(ax3,'Batch','f_r','Repetition rate');
        if givenfD
            hold(ax3,'on'); plot(ax3, ts, param.knownfD(1:N)); hold(ax3,'off');
            uistack(p,'top');
        end
        p = plot(ax1, mean(tsf(:,pxk(:,lf0)~=0),1), pxk(pxk(:,lf0)~=0,lf0)/Ts);
        if givenf0
            hold(ax1,'on'); plot(ax1, ts, param.knownf0(1:N)); hold(ax1,'off');
            uistack(p,'top');
        end
        xyt(ax1,'Batch','f_0','Offset');
        semilogy(ax4, n, abs(Av).^2);
        xyt(ax4,'n','Power','Current power estimate');
        drawnow limitrate nocallbacks;  % optional but helps a lot
        lastplot = toc;
    end

   
    k=k+1;
    % Initializations
    % When we start, we have no idea what the interferogram looks like, so our demodulated estimates are bad.
    % Therefore, once some data has been processed, we run the standard Kalman filter backwards from the last
    % processed batch to the first timestep, then restart the forward pass using the backward filter's x and P
    % value at the first timestep.
    if k>initk && initsleft>0 && ~givenA
        K = k-1;                                    % last forward batch processed

        % Weighted-average line amplitudes used for the backward measurement updates
        nn = find(~isnan(An(1,:)));
        Avb = sum(An(:,nn).*lgf(nn),2)./sum(lgf(nn));

        xkni = cell(K,1);                           % backward-filtered trajectory (for plotting/convergence)
        xkk = reshape(xk(K,:),length(x0),1);        % seed backward filter with the forward estimate at batch K
        % (Pkk already holds the forward covariance at batch K)
        xkni{K} = xkk;
        for ki = K-1:-1:1
            % Backward (reverse-time) prediction from batch ki+1 to batch ki
            Fb = inv(Fs{ki+1});
            Qb = Fb*Qs{ki+1}*Fb';
            xkkm1 = Fb*xkk;
            Pkkm1 = Fb*Pkk*Fb' + Qb;
            Pkkm1 = (Pkkm1+Pkkm1')/2;

            % Measurement update at batch ki (standard Kalman filter step)
            k = ki;                                 % batch_update reads the shared k
            Av = Avb;
            Av(abs(xkkm1(lf0)+n*xkkm1(lfD))>1/dt) = 0;   % zero lines outside the Nyquist band
            batch_update();                              % writes xkk, Pkk
            Pkk = (Pkk+Pkk')/2;
            xkni{ki} = xkk;
        end

        if isinf(initsleft)
            % Adaptive initialization: wait until frequencies change by less than inittol
            if ~isempty(lastf)
                 % RMS frequency change in units of the rep rate
                df = sqrt(mean(mean(abs(xk(1:K,lf0)+xk(1:K,lfD).*n - lastf).^2)))./mean(xk(1:K,lfD));
            else
                df = Inf;
            end
            lastf = xk(1:K,lf0)+xk(1:K,lfD).*n;
            Ninits = Ninits + 1;
            
            if df < param.inittol || Ninits > param.maxinits
                initsleft = 0;
            end
        else
            % Non-adaptive: do a preset number of iters
            initsleft=initsleft-1;
        end
        
        pxkn = cell2mat(xkni').';
        did_init = true;
        k=1; 
        x0 = xkk;                                   % backward estimate at batch 1
        % x0 = xkk;
        P0 = Pkk;                                   % backward covariance at batch 1
    end
end,toc

% residpwr = mean(mean(abs(snr-pkk).^2));
% sigpower = mean(mean(abs(snr).^2));
err=mean(mean(abs(snr-pkk).^2));                                     % fractional error

if ~isfield(param,'skip_correction') || param.skip_correction==0
% Correction can be skipped entirely, which avoids the FFTs of large signals. In this case the output of the filter
% is basically the line amplitudes (An)
    %% RTS smoothing
    xkn = xk;
    [xkns,Pkns,Exkxkp1p] = deal(cell(Nb,1));
    for k=Nb:-1:1
        xkk = reshape(xk(k,:),length(x0),1);
        if k==Nb
            xkn(k,:) = xkk.';
            xkns{k} = xkn(k,:).';
            Pkns{k} = Pkks{k};
        else    
            xkn(k,:) = (xkk + Ck{k+1}*(xkn(k+1,:).'-xkkm1s{k+1})).'; 
            if doEM==1
                xkns{k} = xkn(k,:).';
                Pkns{k} = Pkks{k} + Ck{k+1}*(Pkns{k+1}-Pkkm1s{k+1})*Ck{k+1}'; Pkns{k}=(Pkns{k}+Pkns{k}')/2;
                Exkxkp1p{k}=xkk*xkn(k+1,:) + Ck{k+1}*(Pkns{k+1}+(xkn(k+1,:)'-xkkm1s{k+1})*xkn(k+1,:));  % expected x_k * x_{k+1}'
            end
        end
    end

    %% Resample onto a 1-timestep grid and perform post-regularization
    [ws,p0,pD,varp0,varpD] = deal(zeros(size(sn)));
    for k=1:Nb
        p0(starts(k):fstops(k)) = xkn(k,lp0)+2*pi*(ts(starts(k):fstops(k))-ts(starts(k)))*xkn(k,lf0);
        pD(starts(k):fstops(k)) = xkn(k,lpD)+2*pi*(ts(starts(k):fstops(k))-ts(starts(k)))*xkn(k,lfD);
        ws(starts(k):stops(k))=abs(sn(starts(k):stops(k))).^2;

        P = Pkns{k};
        varp0(starts(k):stops(k)) = P(lp0,lp0)+P(lp0,lf0)*2*pi*tk+2*pi*tk*P(lf0,lp0)+(2*pi*tk).^2*P(lf0,lf0);
        varpD(starts(k):stops(k)) = P(lpD,lpD)+P(lpD,lfD)*2*pi*tk+2*pi*tk*P(lfD,lpD)+(2*pi*tk).^2*P(lfD,lfD);
    end

    % If desired, unprocessed parts by interpolating
    if isfield(param,'fullsignal') && param.fullsignal
        br = [1:starts(1)-1,stops(end)+1:length(sn)];
        p0(br) = interp1(ts(vr),p0(vr),ts(br),'linear','extrap');
        pD(br) = interp1(ts(vr),pD(vr),ts(br),'linear','extrap');
        % ws(br) = abs(sn(br)).^2;
        vr = 1:length(sn);
    end

    % ws = ws(vr);
    p0 = p0(vr); pD = pD(vr);

    if paramis('post_regularization','ekf') || paramis('EM','ekf')
        % One-timestep EKF regularization linearized around batch solution
        EM_ekf = paramis('EM','ekf');
        nn = find(~isnan(An(1,:)));
        Av = sum(An(:,nn).*lgf(nn),2)./sum(lgf(nn));  % weighted average
        % Number of samples in the init region to exclude from EM
        if did_init && initk > 0
            em_exclude_samples = stops(initk) - starts(1) + 1;
        else
            em_exclude_samples = 0;
        end
        [p0ekf, pDekf, Q_EM, nstd_EM] = OneStep_EKF_Regularization(ts(vr), sn(vr), p0, pD, n, Av, nstd, Q, M0, dt, EM_ekf, em_exclude_samples);
        if paramis('post_regularization','ekf')
            p0 = p0ekf; pD = pDekf;
        end
    end

    if paramis('post_regularization','lpf')
        % Low pass filter under the assumption that noise is bandlimited
        fDm = (pD(end)-pD(1))/(ts(vr(end))-ts(vr(1)))/2/pi;
        p0m = (p0(end)-p0(1))/(ts(vr(end))-ts(vr(1)))*(ts(vr)-ts(vr(1)))+p0(1);
        pDm = (pD(end)-pD(1))/(ts(vr(end))-ts(vr(1)))*(ts(vr)-ts(vr(1)))+pD(1);

        w0 = 1./varp0; w0(varp0==0)=0;
        wD = 1./varpD; wD(varpD==0)=0;
        
        % p02 = Weighted_LPF(ts(vr),p0-p0m,fDm/2,ws); p0 = p02+p0m;
        % pD2 = Weighted_LPF(ts(vr),pD-pDm,fDm/2,ws); pD = pD2+pDm;
        [p02, ~] = Rubber_Band_Filter_Inline(ts(vr), p0-p0m, fDm/2, 'ws',w0(vr)); p0 = p02 + p0m;
        [pD2, ~] = Rubber_Band_Filter_Inline(ts(vr), pD-pDm, fDm/2, 'ws',wD(vr)); pD = pD2 + pDm;
    end
    f0 = diff(p0)/dt/2/pi; f0=[f0;f0(end)];
    fD = diff(pD)/dt/2/pi; fD=[fD;fD(end)];


    %% Correct the signal!
    output = Correct_Signal(data.sn(vr,:),dt,p0,pD);
    if param.plotme
        ax2=subplot(2,2,2,'Parent',fh);
        semilogy(ax2,output.fssDc/1e6,output.Psn_fDc);
        xlim(ax2,[-1,1]*1/dt/2/1e6);
        xyt(ax2,'Frequency (MHz)','PSD','Corrected PSD');
    end

    %% Expectation maximization
    % Sometimes there are precision issues with the traces, so compute
    % traces by collecting all terms and using compensated summation.
    % Requires XSum on the path
    if paramis('EM','ekf')
        output.Q_EM = Q_EM;
        output.excess_noise_EM = nstd_EM/nstd*param.excess_noise;
    elseif doEM
        [Qt1,Qt2,Qt3,Qt4,Qt5,Qt6]=deal(zeros(4,4,Nb-1));
        for k=1:Nb-1
            Qt1(:,:,k) = Pkns{k+1}/(Md(k+1)/M0);
            Qt2(:,:,k) = xkns{k+1}*xkns{k+1}'/(Md(k+1)/M0);
            Qt3(:,:,k) = -Fs{k+1}*Exkxkp1p{k}/(Md(k+1)/M0);
            Qt4(:,:,k) = -Exkxkp1p{k}'*Fs{k+1}'/(Md(k+1)/M0);
            Qt5(:,:,k) = Fs{k+1}*Pkns{k}*Fs{k+1}'/(Md(k+1)/M0);
            Qt6(:,:,k) = Fs{k+1}*xkns{k}*xkns{k}'*Fs{k+1}'/(Md(k+1)/M0);
        end                   
        % Weight: zero in init region, hanning over the rest
        if did_init && initk > 0
            wk = zeros(Nb-1, 1);
            nh = Nb - 1 - initk;
            if nh > 0, wk(initk+1:end) = hanning(nh); end
        else
            wk = hanning(Nb-1); wk(1)=0;
        end
        wk = reshape(wk,1,1,Nb-1);              % deweight the edges
        Qtm = XSum(cat(3,Qt1.*wk,Qt2.*wk,Qt3.*wk,Qt4.*wk,Qt5.*wk,Qt6.*wk),3)/sum(wk);
        output.Q_EM = Qtm;

        trms=zeros(1+1+4+4,Nb);
        for k=1:Nb
            [hv,Hv]=hH(xkns{k},GI,GIn);
            Ck = [real(snr(:,k));imag(snr(:,k))]-hv+Hv*xkns{k};
            trms(:,k) = [Ck'*Ck;-Ck'*Hv*xkns{k};-diag(Hv'*Ck*xkns{k}');diag(Hv'*Hv*(Pkns{k}+xkns{k}*xkns{k}'))];
        end  
        % Weight: zero in init region, hanning over the rest
        if did_init && initk > 0
            wk = zeros(Nb, 1);
            nh = Nb - initk;
            if nh > 0, wk(initk+1:end) = hanning(nh); end
        else
            wk = hanning(Nb); wk(1)=0;
        end
        nstd2 = XSum(reshape(trms.*wk.',size(trms,1)*Nb,1))/sum(wk)/(2*M);   
        output.excess_noise_EM = sqrt(nstd2)/nstd*param.excess_noise;
    end
else
    p0 = xk(:,lp0);
    pD = xk(:,lpD);
    f0 = xk(:,lf0);
    fD = xk(:,lfD);
    output = struct();
end


%% Set up the output structure
output.n = n;                   % index of each line
output.An = An.';               % instantaneous estimate of amplitude of each batch. This is always noisy...needs to be averaged
output.tb = mean(ts(bl),1)';    % average time of each batch (possibly non-uniform)

output.err = err;
output.npsd = 2*nstd^2*dt;   
output.QM = Q;
output.M  = M;
output.sn = sn(vr,:);
output.ts = dt*(0:length(sn)-1)'*Ts;
output.ts = output.ts(vr);
output.p0 = p0;
output.pD = pD;
output.f0 = f0;
output.fD = fD;
output.data  = data;
output.param = param;

% Restore time axis units
output.npsd  = output.npsd*Ts;
output.f0    = output.f0/Ts;
output.fD    = output.fD/Ts;
if ~isfield(param,'skip_correction') || param.skip_correction==0
    output.tsDc = output.tsDc*Ts;
    output.dtDc = output.dtDc*Ts;
    output.fssDc = output.fssDc/Ts;
    output.fss0c = output.fss0c/Ts;
    output.fss   = output.fss  /Ts;
    output.Psn_fDc = output.Psn_fDc*Ts;
    output.Psn_f0c = output.Psn_f0c*Ts;
    output.Psn     = output.Psn    *Ts;
end
end

function [p0_out, pD_out, Q_EM, nstd_EM] = OneStep_EKF_Regularization(ts, sn, p0_batch, pD_batch, n, A_batch, nstd, Q_batch, M0, dt, do_EM, em_exclude_samples)
% ONESTEP_EKF_REGULARIZATION: Post-regularization using one-timestep EKF
% linearized around the RTS smoothed batch solution
%
% Inputs:
%   ts:         Time vector (N x 1)
%   sn:         Actual complex signal (N x 1)
%   p0_batch:   Batch-estimated phase offset trajectory (N x 1)
%   pD_batch:   Batch-estimated rep rate phase trajectory (N x 1)
%   n:          Line indices (1 x Nl)
%   A_batch:    Average line amplitudes from batch estimate (Nl x 1)
%   nstd:       Measurement noise standard deviation
%   Q_batch:    Process noise covariance for batch (4 x 4)
%   M0:         Batch size (used to scale Q to single timestep)
%   dt:         Timestep (scalar, already normalized)
%   do_EM:      Whether to compute EM updates
%   em_exclude_samples: Number of samples at the start to exclude from EM
%
% Outputs:
%   p0_out:     Regularized phase offset trajectory (N x 1)
%   pD_out:     Regularized rep rate phase trajectory (N x 1)

if nargin < 12
    em_exclude_samples = 0;
end

N = length(ts);

% State indices
lp0 = 1; lpD = 2; lf0 = 3; lfD = 4;



% Process model (single timestep)
F = eye(4);
F(lpD, lfD) = F(lpD, lfD) + 2*pi*dt;
F(lp0, lf0) = F(lp0, lf0) + 2*pi*dt;

% Scale process noise from batch to single timestep
Q = Qbatch_to_Qstep(F, Q_batch, M0);

% Measurement noise covariance
R = eye(2) * nstd^2;

% Initialize state from batch solution
f0_batch = [diff(p0_batch)/dt/2/pi; diff(p0_batch(end-1:end))/dt/2/pi];
fD_batch = [diff(pD_batch)/dt/2/pi; diff(pD_batch(end-1:end))/dt/2/pi];

% Setup interpolants for fast evaluation of p(t) using batch amplitudes
ZPF = 5;
oms = -max(abs(n))*ZPF : max(abs(n))*ZPF;
[~, nidx] = ismember(n, oms);
px = linspace(0, 2*pi, length(oms)+1);

% Create interpolants for p0(phi) and p1(phi) = n*p0(phi)
function GIout = Make_GI(Ain)
    Aom = zeros(size(oms));
    Aom(nidx) = Ain(:);  % Ensure column vector
    py = length(oms) * ifft(ifftshift(Aom));
    py = py(:);  % Ensure column vector
    py = [py; py(1)];  % Make 2pi periodic
    GIout = griddedInterpolant(px(:), py, 'cubic');
end

p0_interp = Make_GI(A_batch);
p1_interp = Make_GI(n .* A_batch.');

% Measurement function and Jacobian
function [hvo, Hvo] = hH(xin)
    expv = exp(1i * xin(lp0));
    phi_mod = mod(xin(lpD), 2*pi);
    p0_val = p0_interp(phi_mod);
    p1_val = p1_interp(phi_mod);
    
    hvo = expv * p0_val;
    Hvo = [1i*hvo, 1i*expv*p1_val, 0, 0];
end

% Storage for filtered estimates
xk_filt = zeros(N, 4);
Pk_filt = cell(N, 1);

% Initial state and covariance from batch solution
x0 = [p0_batch(1); pD_batch(1); f0_batch(1); fD_batch(1)];
P0 = eye(4) * 1e-6;  % Small initial uncertainty since we're near the solution

xkk = x0;
Pkk = P0;

% Forward filtering pass
for k = 1:N
    % Prediction step
    xkkm1 = F * xkk;
    Pkkm1 = F * Pkk * F' + Q;
    Pkkm1 = (Pkkm1 + Pkkm1') / 2;  % Ensure symmetry
    
    % Get actual measurement from signal
    meas = sn(k);
    
    % Evaluate h at predicted state (nonlinear)
    % [hc_pred, ~] = hH(xkkm1);
    
    % Evaluate H at BATCH SOLUTION at this timestep (linearization point)
    x_linearize = [p0_batch(k); pD_batch(k); f0_batch(k); fD_batch(k)];
    [hclin, Hc] = hH(x_linearize);
    
    % Innovation
    ykc = meas - (hclin + Hc*(xkkm1 - x_linearize));
    yk = [real(ykc); imag(ykc)];
    Hv = [real(Hc); imag(Hc)];
    
    % Kalman gain
    S = Hv * Pkkm1 * Hv' + R;
    Kk = Pkkm1 * Hv' / S;
    
    % Update step
    xkk = xkkm1 + Kk * yk;
    
    % Joseph form for numerical stability
    IKH = eye(4) - Kk * Hv;
    Pkk = IKH * Pkkm1 * IKH' + Kk * R * Kk';
    Pkk = (Pkk + Pkk') / 2;  % Ensure symmetry
    
    % Store
    xk_filt(k, :) = xkk';
    Pk_filt{k} = Pkk;
end

% RTS Smoothing (backward pass)
% Start with filtered estimates
xk_smooth = xk_filt;
Pk_smooth = Pk_filt;

for k = N-1:-1:1
    % Recompute one-step-ahead prediction from k
    x_pred = F * xk_filt(k, :)';
    Pk_pred = F * Pk_filt{k} * F' + Q;
    Pk_pred = (Pk_pred + Pk_pred') / 2;
    
    % RTS smoother gain
    Ck = Pk_filt{k} * F' / Pk_pred;
    if do_EM
        Ck_smooth{k} = Ck;  % Store for EM
    end
    
    % Smoothed state: x_{k|N} = x_{k|k} + C_k * (x_{k+1|N} - x_{k+1|k})
    xk_smooth(k, :) = (xk_filt(k, :)' + Ck * (xk_smooth(k+1, :)' - x_pred))';
    
    % Smoothed covariance: P_{k|N} = P_{k|k} + C_k * (P_{k+1|N} - P_{k+1|k}) * C_k'
    Pk_smooth{k} = Pk_filt{k} + Ck * (Pk_smooth{k+1} - Pk_pred) * Ck';
    Pk_smooth{k} = (Pk_smooth{k} + Pk_smooth{k}') / 2;
end

p0_out = xk_smooth(:, lp0);
pD_out = xk_smooth(:, lpD);

% Expectation Maximization
if do_EM
        % === Build x_{k|N} and P_{k|N} as column vectors/matrices ===
    xkns = cell(N,1);
    Pkns = cell(N,1);
    for k = 1:N
        xkns{k} = xk_smooth(k,:).';     % 4x1
        Pkns{k} = Pk_smooth{k};         % 4x4
    end

    % === Build Exkxkp1p{k} = E[x_k x_{k+1}^T] in the SAME STYLE as batch code ===
    % In your batch code:
    % Exkxkp1p{k}=xkk*xkn(k+1,:) + Ck{k+1}*(Pkns{k+1}+(xkn(k+1,:)'-xkkm1s{k+1})*xkn(k+1,:));
    %
    % For one-step: xkkm1s{k+1} is the predicted mean x_{k+1|k} = F*x_{k|k}
    % and Ck_smooth{k} is the RTS smoother gain at time k (maps k+1 residual back to k).
    Exkxkp1p = cell(N-1,1);
    for k = 1:N-1
        % predicted x_{k+1|k} from FILTERED estimate at k
        xkk     = xk_filt(k,:).';            % x_{k|k}
        xkkm1   = F * xkk;                   % x_{k+1|k}
        Ck1     = Ck_smooth{k};              % RTS gain at time k

        xkp1N   = xkns{k+1};                 % x_{k+1|N}
        Pkp1N   = Pkns{k+1};                 % P_{k+1|N}

        % This matches your batch expression structure:
        % x_k x_{k+1|N}^T  +  C_k * ( P_{k+1|N} + (x_{k+1|N}-x_{k+1|k}) x_{k+1|N}^T )
        Exkxkp1p{k} = xkk * (xkp1N.') + Ck1 * ( Pkp1N + (xkp1N - xkkm1) * (xkp1N.') );
    end

    % === Q EM: mirror your batch Qt1..Qt6 accumulation with Md/M0 = 1/M0 ===
    % In batch: each term is divided by (Md(k+1)/M0). Here Md=1 always -> divide by (1/M0) = multiply by M0.
    % Equivalently: since our process model is already one-step, we estimate Qstep directly.
    % Then if you want a "batch-equivalent" Q, multiply by M0 outside.
    %
    % We'll estimate Qstep here to be consistent with the one-step process model.
    [Qt1,Qt2,Qt3,Qt4,Qt5,Qt6] = deal(zeros(4,4,N-1));
    for k = 1:N-1
        Qt1(:,:,k) = Pkns{k+1};
        Qt2(:,:,k) = xkns{k+1}*xkns{k+1}';
        Qt3(:,:,k) = -F*Exkxkp1p{k};
        Qt4(:,:,k) = -Exkxkp1p{k}'*F';
        Qt5(:,:,k) = F*Pkns{k}*F';
        Qt6(:,:,k) = F*xkns{k}*xkns{k}'*F';
    end

    % Weight: zero in init region, hanning over the rest
    if em_exclude_samples > 0
        wk = zeros(N-1, 1);
        nh = N - 1 - em_exclude_samples;
        if nh > 0, wk(em_exclude_samples+1:end) = hanning(nh); end
    else
        wk = hanning(N-1); wk(1)=0;
    end
    wk = reshape(wk,1,1,N-1);

    Q_EM = XSum(cat(3,Qt1.*wk,Qt2.*wk,Qt3.*wk,Qt4.*wk,Qt5.*wk,Qt6.*wk),3) / sum(wk);
    Q_EM = (Q_EM + Q_EM')/2;

    % Convert back to batch Q
    Q_EM = Qstep_to_Qbatch(F, Q_EM, M0);

    % === Measurement noise EM: reuse the SAME trace structure idea ===
    % Your batch code forms:
    % Ck = y - h(x) + Hx
    % trms collects Ck'*Ck, -Ck'*H x, etc, and computes nstd2 = sum / (2*M)
    %
    % Here measurement is scalar complex (2 real dims) per time step -> "M=1".
    trms = zeros(1+1+4+4, N);
    for k = 1:N
        % linearize at your chosen point (batch trajectory)
        x_lin = [p0_batch(k); pD_batch(k); f0_batch(k); fD_batch(k)];
        [hc, Hc] = hH(x_lin);

        yv = [real(sn(k)); imag(sn(k))];
        hv = [real(hc);   imag(hc)];
        Hv = [real(Hc);   imag(Hc)];

        Cvec = yv - (hv - Hv * x_lin);  % matches your batch definition (Ck)

        % trms(:,k) = [ ...
        %     Cvec.'*Cvec; ...
        %     -Cvec.'*Hv*x_lin; ...
        %     -diag(Hv.'*Cvec*x_lin.'); ...
        %      diag(Hv.'*Hv*(Pkns{k}+x_lin*x_lin.')) ...
        % ];
        trms(:,k) = [ ...
            Cvec.'*Cvec; ...
            -Cvec.'*Hv*xkns{k};
            -diag(Hv.'*Cvec*xkns{k}.');
             diag(Hv.'*Hv*(Pkns{k} + xkns{k}*xkns{k}.'));
        ];
    end

    % Weight: zero in init region, hanning over the rest
    if em_exclude_samples > 0
        wk = zeros(N, 1);
        nh = N - em_exclude_samples;
        if nh > 0, wk(em_exclude_samples+1:end) = hanning(nh); end
    else
        wk = hanning(N); wk(1)=0;
    end
    % 2 real quadratures per sample -> divide by (2*1)
    nstd2 = XSum(reshape(trms.*wk.', size(trms,1)*N, 1)) / sum(wk) / 2;
    nstd_EM = sqrt(nstd2);
else
    Q_EM = [];
    nstd_EM = [];
end

end

function Qstep = Qbatch_to_Qstep(F, Qbatch, m)
n = size(F,1);
A = zeros(n*n,n*n);
Fj = eye(n);
for j = 1:m
    A = A + kron(Fj,Fj);
    Fj = F*Fj;
end
Qstep = reshape(A \ Qbatch(:), n, n);

% Enforce positive semi-definite
[V,D] = eig(Qstep);
D(D<0) = 0;
Qstep = V*D*V';
Qstep = (Qstep+Qstep')/2;
end

function Qbatch = Qstep_to_Qbatch(F, Qstep, m)

% Enforce positive semi-definite
[V,D] = eig(Qstep);
D(D<0) = 0;
Qstep = V*D*V';
Qstep = (Qstep+Qstep')/2;

n = size(F,1);
Qbatch = zeros(n);
Fj = eye(n);
for j = 1:m
    Qbatch = Qbatch + Fj*Qstep*Fj';
    Fj = F*Fj;
end
Qbatch = (Qbatch + Qbatch')/2;
end